# Generated by Django 4.1.1 on 2022-09-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('puffs', models.CharField(max_length=4)),
                ('sabor', models.CharField(max_length=100)),
                ('custo', models.IntegerField()),
                ('qtd_stock', models.IntegerField()),
                ('custo_venda', models.IntegerField()),
            ],
        ),
    ]
