# Generated by Django 4.1.1 on 2022-09-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_marcaproduto_alter_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
