# Generated by Django 4.1.1 on 2022-09-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosvenda',
            name='hora',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosvenda',
            name='produtoinfo',
            field=models.CharField(max_length=68),
        ),
    ]
