# Generated by Django 4.1.1 on 2022-09-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_produto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='produto_fk',
        ),
    ]
