# Generated by Django 4.1.1 on 2022-09-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_produto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estado',
            new_name='vendido',
        ),
    ]
