# Generated by Django 4.1.1 on 2022-09-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_dadosvenda_dia_alter_dadosvenda_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosvenda',
            name='dia',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='dadosvenda',
            name='hora',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosvenda',
            name='produtoinfo',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='dadosvenda',
            name='quantidade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='puffs',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sabor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
