# Generated by Django 4.1.1 on 2022-09-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_estado_produto_vendido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='custo',
            new_name='custo_produto',
        ),
    ]
