# Generated by Django 4.1.1 on 2022-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_custo_produto_custo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='MarcaProduto',
        ),
    ]
