# Generated by Django 4.1.1 on 2022-09-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_dadosvenda_dia_alter_dadosvenda_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=68)),
                ('lucro_tot', models.IntegerField(default=0)),
                ('preco_tot', models.IntegerField(default=0)),
                ('custo_tot', models.IntegerField(default=0)),
            ],
        ),
    ]
