# Generated by Django 4.1.1 on 2022-09-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='produto',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='marca',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='puffs',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sabor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
