# Generated by Django 4.1.1 on 2022-09-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_produto_marca_delete_marcaproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qtd_stock',
        ),
    ]
