# Generated by Django 4.1.1 on 2022-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_produto_qtd_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
    ]
