# Generated by Django 4.1.1 on 2022-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
        migrations.AddField(
            model_name='produto',
            name='idprod',
            field=models.AutoField(default=True, primary_key=True, serialize=False, unique=True, verbose_name='<django.db.models.fields.CharField>-'),
        ),
    ]
