# Generated by Django 4.1.1 on 2022-09-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_dashboard_custo_tot_alter_dashboard_lucro_tot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
