# Generated by Django 4.1.1 on 2022-09-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_dashboard_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosvenda',
            name='comprador',
            field=models.CharField(default='Não Informado', max_length=60),
        ),
    ]
