# Generated by Django 4.1.1 on 2022-09-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_dadosvenda_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
