# Generated by Django 4.1.1 on 2022-09-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_produto_idprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
