# Generated by Django 4.1.1 on 2022-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('puffs', models.CharField(max_length=4)),
                ('sabor', models.CharField(max_length=100)),
                ('custo_produto', models.IntegerField()),
                ('custo_venda', models.IntegerField()),
                ('vendido', models.BooleanField(default=False)),
            ],
        ),
    ]
