# Generated by Django 4.1.1 on 2022-09-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='custo_produto',
            new_name='custo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='custo_venda',
            new_name='preco',
        ),
    ]
