# Generated by Django 4.1.1 on 2022-09-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_custo_produto_produto_custo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendido',
        ),
    ]
