# Generated by Django 4.1.1 on 2022-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_produto_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
