# Generated by Django 4.1.1 on 2022-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
