# Generated by Django 4.1.1 on 2022-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_produto_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtoinfo', models.CharField(max_length=60)),
                ('dia', models.CharField(max_length=12)),
                ('hora', models.CharField(max_length=8)),
            ],
        ),
    ]
