# Generated by Django 4.1.1 on 2022-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_dadosvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
