# Generated by Django 4.1.1 on 2022-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_dadosvenda_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosvenda',
            name='quantidade',
            field=models.CharField(max_length=2),
        ),
    ]
