# Generated by Django 4.1.1 on 2022-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_dadosvenda_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='idprod',
            field=models.IntegerField(default=1),
        ),
    ]
