# Generated by Django 4.1.1 on 2022-09-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_produto_idprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='idprod',
        ),
    ]
